//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPAP.TimboxWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WashOut", ConfigurationName="TimboxWS.timbrado_cfdi33_port")]
    public interface timbrado_cfdi33_port {
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrar_cfdi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="timbrar_cfdi_result")]
        SOAPAP.TimboxWS.timbrar_cfdi_result timbrar_cfdi(string username, string password, string sxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrar_cfdi", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="timbrar_cfdi_result")]
        System.Threading.Tasks.Task<SOAPAP.TimboxWS.timbrar_cfdi_result> timbrar_cfdiAsync(string username, string password, string sxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrar_cfdi_referencia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="timbrar_cfdi_referencia_result")]
        SOAPAP.TimboxWS.timbrar_cfdi_referencia_result timbrar_cfdi_referencia(string username, string password, string sxml, string external_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrar_cfdi_referencia", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="timbrar_cfdi_referencia_result")]
        System.Threading.Tasks.Task<SOAPAP.TimboxWS.timbrar_cfdi_referencia_result> timbrar_cfdi_referenciaAsync(string username, string password, string sxml, string external_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrar_zip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="timbrar_zip_result")]
        SOAPAP.TimboxWS.timbrar_zip_result timbrar_zip(string username, string password, string zipbase64);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrar_zip", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="timbrar_zip_result")]
        System.Threading.Tasks.Task<SOAPAP.TimboxWS.timbrar_zip_result> timbrar_zipAsync(string username, string password, string zipbase64);
        
        [System.ServiceModel.OperationContractAttribute(Action="buscar_cfdis", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="buscar_cfdis_result")]
        SOAPAP.TimboxWS.buscar_cfdis_result buscar_cfdis(string username, string password, SOAPAP.TimboxWS.parametros_cfdis parametros_cfdis);
        
        [System.ServiceModel.OperationContractAttribute(Action="buscar_cfdis", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="buscar_cfdis_result")]
        System.Threading.Tasks.Task<SOAPAP.TimboxWS.buscar_cfdis_result> buscar_cfdisAsync(string username, string password, SOAPAP.TimboxWS.parametros_cfdis parametros_cfdis);
        
        [System.ServiceModel.OperationContractAttribute(Action="buscar_acuse_recepcion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="buscar_acuse_recepcion_result")]
        SOAPAP.TimboxWS.buscar_acuse_recepcion_result buscar_acuse_recepcion(string username, string password, SOAPAP.TimboxWS.parametros_acuse parametros_acuse);
        
        [System.ServiceModel.OperationContractAttribute(Action="buscar_acuse_recepcion", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="buscar_acuse_recepcion_result")]
        System.Threading.Tasks.Task<SOAPAP.TimboxWS.buscar_acuse_recepcion_result> buscar_acuse_recepcionAsync(string username, string password, SOAPAP.TimboxWS.parametros_acuse parametros_acuse);
        
        [System.ServiceModel.OperationContractAttribute(Action="recuperar_comprobante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="recuperar_comprobante_result")]
        SOAPAP.TimboxWS.recuperar_comprobante_result recuperar_comprobante(string username, string password, SOAPAP.TimboxWS.uuid uuids);
        
        [System.ServiceModel.OperationContractAttribute(Action="recuperar_comprobante", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="recuperar_comprobante_result")]
        System.Threading.Tasks.Task<SOAPAP.TimboxWS.recuperar_comprobante_result> recuperar_comprobanteAsync(string username, string password, SOAPAP.TimboxWS.uuid uuids);
        
        [System.ServiceModel.OperationContractAttribute(Action="recuperar_comprobante_referencia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="recuperar_comprobante_referencia")]
        SOAPAP.TimboxWS.recuperar_comprobante_referencia recuperar_comprobante_referencia(string username, string password, SOAPAP.TimboxWS.external_id external_ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="recuperar_comprobante_referencia", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="recuperar_comprobante_referencia")]
        System.Threading.Tasks.Task<SOAPAP.TimboxWS.recuperar_comprobante_referencia> recuperar_comprobante_referenciaAsync(string username, string password, SOAPAP.TimboxWS.external_id external_ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="obtener_consumo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="obtener_consumo_result")]
        SOAPAP.TimboxWS.obtener_consumo_result obtener_consumo(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="obtener_consumo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="obtener_consumo_result")]
        System.Threading.Tasks.Task<SOAPAP.TimboxWS.obtener_consumo_result> obtener_consumoAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="consulta_rfc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="consulta_rfc_result")]
        SOAPAP.TimboxWS.consulta_rfc_result consulta_rfc(string username, string password, string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="consulta_rfc", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="consulta_rfc_result")]
        System.Threading.Tasks.Task<SOAPAP.TimboxWS.consulta_rfc_result> consulta_rfcAsync(string username, string password, string rfc);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class timbrar_cfdi_result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
                this.RaisePropertyChanged("xml");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class consulta_rfc_result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string statusField;
        
        private string informacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string informacion {
            get {
                return this.informacionField;
            }
            set {
                this.informacionField = value;
                this.RaisePropertyChanged("informacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class obtener_consumo_result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string plan_actualField;
        
        private System.Nullable<int> creditos_asignadosField;
        
        private System.Nullable<int> creditos_usadosField;
        
        private string inicio_planField;
        
        private string fin_planField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string plan_actual {
            get {
                return this.plan_actualField;
            }
            set {
                this.plan_actualField = value;
                this.RaisePropertyChanged("plan_actual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> creditos_asignados {
            get {
                return this.creditos_asignadosField;
            }
            set {
                this.creditos_asignadosField = value;
                this.RaisePropertyChanged("creditos_asignados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> creditos_usados {
            get {
                return this.creditos_usadosField;
            }
            set {
                this.creditos_usadosField = value;
                this.RaisePropertyChanged("creditos_usados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inicio_plan {
            get {
                return this.inicio_planField;
            }
            set {
                this.inicio_planField = value;
                this.RaisePropertyChanged("inicio_plan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fin_plan {
            get {
                return this.fin_planField;
            }
            set {
                this.fin_planField = value;
                this.RaisePropertyChanged("fin_plan");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class recuperar_comprobante_referencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estatusField;
        
        private string cantidadField;
        
        private string comprobantesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("estatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string comprobantes {
            get {
                return this.comprobantesField;
            }
            set {
                this.comprobantesField = value;
                this.RaisePropertyChanged("comprobantes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class external_id : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] external_id1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute("external_id", IsNullable=true)]
        public string[] external_id1 {
            get {
                return this.external_id1Field;
            }
            set {
                this.external_id1Field = value;
                this.RaisePropertyChanged("external_id1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class recuperar_comprobante_result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estatusField;
        
        private string cantidadField;
        
        private string comprobantesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("estatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string comprobantes {
            get {
                return this.comprobantesField;
            }
            set {
                this.comprobantesField = value;
                this.RaisePropertyChanged("comprobantes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class buscar_acuse_recepcion_result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string acusesField;
        
        private uuid uuids_erroneosField;
        
        private uuid uuids_no_encontradosField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string acuses {
            get {
                return this.acusesField;
            }
            set {
                this.acusesField = value;
                this.RaisePropertyChanged("acuses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public uuid uuids_erroneos {
            get {
                return this.uuids_erroneosField;
            }
            set {
                this.uuids_erroneosField = value;
                this.RaisePropertyChanged("uuids_erroneos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public uuid uuids_no_encontrados {
            get {
                return this.uuids_no_encontradosField;
            }
            set {
                this.uuids_no_encontradosField = value;
                this.RaisePropertyChanged("uuids_no_encontrados");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class uuid : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] uuid1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute("uuid", IsNullable=true)]
        public string[] uuid1 {
            get {
                return this.uuid1Field;
            }
            set {
                this.uuid1Field = value;
                this.RaisePropertyChanged("uuid1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class parametros_acuse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private uuid uuidsField;
        
        private string fecha_timbrado_inicioField;
        
        private string fecha_timbrado_finField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public uuid uuids {
            get {
                return this.uuidsField;
            }
            set {
                this.uuidsField = value;
                this.RaisePropertyChanged("uuids");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fecha_timbrado_inicio {
            get {
                return this.fecha_timbrado_inicioField;
            }
            set {
                this.fecha_timbrado_inicioField = value;
                this.RaisePropertyChanged("fecha_timbrado_inicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fecha_timbrado_fin {
            get {
                return this.fecha_timbrado_finField;
            }
            set {
                this.fecha_timbrado_finField = value;
                this.RaisePropertyChanged("fecha_timbrado_fin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class buscar_cfdis_result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estatusField;
        
        private string cantidadField;
        
        private string comprobantesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("estatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string comprobantes {
            get {
                return this.comprobantesField;
            }
            set {
                this.comprobantesField = value;
                this.RaisePropertyChanged("comprobantes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class parametros_cfdis : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rfc_emisorField;
        
        private string rfc_receptorField;
        
        private string fecha_emision_inicioField;
        
        private string fecha_emision_finField;
        
        private string fecha_timbrado_inicioField;
        
        private string fecha_timbrado_finField;
        
        private string canceladoField;
        
        private string external_idField;
        
        private string uuidField;
        
        private string folioField;
        
        private string serieField;
        
        private string limitField;
        
        private string offsetField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rfc_emisor {
            get {
                return this.rfc_emisorField;
            }
            set {
                this.rfc_emisorField = value;
                this.RaisePropertyChanged("rfc_emisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rfc_receptor {
            get {
                return this.rfc_receptorField;
            }
            set {
                this.rfc_receptorField = value;
                this.RaisePropertyChanged("rfc_receptor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fecha_emision_inicio {
            get {
                return this.fecha_emision_inicioField;
            }
            set {
                this.fecha_emision_inicioField = value;
                this.RaisePropertyChanged("fecha_emision_inicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fecha_emision_fin {
            get {
                return this.fecha_emision_finField;
            }
            set {
                this.fecha_emision_finField = value;
                this.RaisePropertyChanged("fecha_emision_fin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fecha_timbrado_inicio {
            get {
                return this.fecha_timbrado_inicioField;
            }
            set {
                this.fecha_timbrado_inicioField = value;
                this.RaisePropertyChanged("fecha_timbrado_inicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fecha_timbrado_fin {
            get {
                return this.fecha_timbrado_finField;
            }
            set {
                this.fecha_timbrado_finField = value;
                this.RaisePropertyChanged("fecha_timbrado_fin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cancelado {
            get {
                return this.canceladoField;
            }
            set {
                this.canceladoField = value;
                this.RaisePropertyChanged("cancelado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string external_id {
            get {
                return this.external_idField;
            }
            set {
                this.external_idField = value;
                this.RaisePropertyChanged("external_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
                this.RaisePropertyChanged("folio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("serie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
                this.RaisePropertyChanged("limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("offset");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class timbrar_zip_result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
                this.RaisePropertyChanged("xml");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class timbrar_cfdi_referencia_result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
                this.RaisePropertyChanged("xml");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface timbrado_cfdi33_portChannel : SOAPAP.TimboxWS.timbrado_cfdi33_port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class timbrado_cfdi33_portClient : System.ServiceModel.ClientBase<SOAPAP.TimboxWS.timbrado_cfdi33_port>, SOAPAP.TimboxWS.timbrado_cfdi33_port {
        
        public timbrado_cfdi33_portClient() {
        }
        
        public timbrado_cfdi33_portClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public timbrado_cfdi33_portClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public timbrado_cfdi33_portClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public timbrado_cfdi33_portClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPAP.TimboxWS.timbrar_cfdi_result timbrar_cfdi(string username, string password, string sxml) {
            return base.Channel.timbrar_cfdi(username, password, sxml);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.TimboxWS.timbrar_cfdi_result> timbrar_cfdiAsync(string username, string password, string sxml) {
            return base.Channel.timbrar_cfdiAsync(username, password, sxml);
        }
        
        public SOAPAP.TimboxWS.timbrar_cfdi_referencia_result timbrar_cfdi_referencia(string username, string password, string sxml, string external_id) {
            return base.Channel.timbrar_cfdi_referencia(username, password, sxml, external_id);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.TimboxWS.timbrar_cfdi_referencia_result> timbrar_cfdi_referenciaAsync(string username, string password, string sxml, string external_id) {
            return base.Channel.timbrar_cfdi_referenciaAsync(username, password, sxml, external_id);
        }
        
        public SOAPAP.TimboxWS.timbrar_zip_result timbrar_zip(string username, string password, string zipbase64) {
            return base.Channel.timbrar_zip(username, password, zipbase64);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.TimboxWS.timbrar_zip_result> timbrar_zipAsync(string username, string password, string zipbase64) {
            return base.Channel.timbrar_zipAsync(username, password, zipbase64);
        }
        
        public SOAPAP.TimboxWS.buscar_cfdis_result buscar_cfdis(string username, string password, SOAPAP.TimboxWS.parametros_cfdis parametros_cfdis) {
            return base.Channel.buscar_cfdis(username, password, parametros_cfdis);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.TimboxWS.buscar_cfdis_result> buscar_cfdisAsync(string username, string password, SOAPAP.TimboxWS.parametros_cfdis parametros_cfdis) {
            return base.Channel.buscar_cfdisAsync(username, password, parametros_cfdis);
        }
        
        public SOAPAP.TimboxWS.buscar_acuse_recepcion_result buscar_acuse_recepcion(string username, string password, SOAPAP.TimboxWS.parametros_acuse parametros_acuse) {
            return base.Channel.buscar_acuse_recepcion(username, password, parametros_acuse);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.TimboxWS.buscar_acuse_recepcion_result> buscar_acuse_recepcionAsync(string username, string password, SOAPAP.TimboxWS.parametros_acuse parametros_acuse) {
            return base.Channel.buscar_acuse_recepcionAsync(username, password, parametros_acuse);
        }
        
        public SOAPAP.TimboxWS.recuperar_comprobante_result recuperar_comprobante(string username, string password, SOAPAP.TimboxWS.uuid uuids) {
            return base.Channel.recuperar_comprobante(username, password, uuids);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.TimboxWS.recuperar_comprobante_result> recuperar_comprobanteAsync(string username, string password, SOAPAP.TimboxWS.uuid uuids) {
            return base.Channel.recuperar_comprobanteAsync(username, password, uuids);
        }
        
        public SOAPAP.TimboxWS.recuperar_comprobante_referencia recuperar_comprobante_referencia(string username, string password, SOAPAP.TimboxWS.external_id external_ids) {
            return base.Channel.recuperar_comprobante_referencia(username, password, external_ids);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.TimboxWS.recuperar_comprobante_referencia> recuperar_comprobante_referenciaAsync(string username, string password, SOAPAP.TimboxWS.external_id external_ids) {
            return base.Channel.recuperar_comprobante_referenciaAsync(username, password, external_ids);
        }
        
        public SOAPAP.TimboxWS.obtener_consumo_result obtener_consumo(string username, string password) {
            return base.Channel.obtener_consumo(username, password);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.TimboxWS.obtener_consumo_result> obtener_consumoAsync(string username, string password) {
            return base.Channel.obtener_consumoAsync(username, password);
        }
        
        public SOAPAP.TimboxWS.consulta_rfc_result consulta_rfc(string username, string password, string rfc) {
            return base.Channel.consulta_rfc(username, password, rfc);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.TimboxWS.consulta_rfc_result> consulta_rfcAsync(string username, string password, string rfc) {
            return base.Channel.consulta_rfcAsync(username, password, rfc);
        }
    }
}
