//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPAP.WsIntegral33Pruebas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Peticion", Namespace="http://schemas.datacontract.org/2004/07/WcfIntegral33")]
    [System.SerializableAttribute()]
    public partial class Peticion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cadenaComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cadenaTXTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool pdfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool productivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rfcEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tipoCFDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cadenaComplemento {
            get {
                return this.cadenaComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.cadenaComplementoField, value) != true)) {
                    this.cadenaComplementoField = value;
                    this.RaisePropertyChanged("cadenaComplemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cadenaTXT {
            get {
                return this.cadenaTXTField;
            }
            set {
                if ((object.ReferenceEquals(this.cadenaTXTField, value) != true)) {
                    this.cadenaTXTField = value;
                    this.RaisePropertyChanged("cadenaTXT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.contrasenaField, value) != true)) {
                    this.contrasenaField = value;
                    this.RaisePropertyChanged("contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool pdf {
            get {
                return this.pdfField;
            }
            set {
                if ((this.pdfField.Equals(value) != true)) {
                    this.pdfField = value;
                    this.RaisePropertyChanged("pdf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool productivo {
            get {
                return this.productivoField;
            }
            set {
                if ((this.productivoField.Equals(value) != true)) {
                    this.productivoField = value;
                    this.RaisePropertyChanged("productivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rfcEmisor {
            get {
                return this.rfcEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.rfcEmisorField, value) != true)) {
                    this.rfcEmisorField = value;
                    this.RaisePropertyChanged("rfcEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tipoCFDI {
            get {
                return this.tipoCFDIField;
            }
            set {
                if ((this.tipoCFDIField.Equals(value) != true)) {
                    this.tipoCFDIField = value;
                    this.RaisePropertyChanged("tipoCFDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/WcfIntegral33")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoConfirmacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorEspecificoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorGeneralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool exitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] pdfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xmlTimbradoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoConfirmacion {
            get {
                return this.codigoConfirmacionField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoConfirmacionField, value) != true)) {
                    this.codigoConfirmacionField = value;
                    this.RaisePropertyChanged("codigoConfirmacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorEspecifico {
            get {
                return this.errorEspecificoField;
            }
            set {
                if ((object.ReferenceEquals(this.errorEspecificoField, value) != true)) {
                    this.errorEspecificoField = value;
                    this.RaisePropertyChanged("errorEspecifico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorGeneral {
            get {
                return this.errorGeneralField;
            }
            set {
                if ((object.ReferenceEquals(this.errorGeneralField, value) != true)) {
                    this.errorGeneralField = value;
                    this.RaisePropertyChanged("errorGeneral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool exito {
            get {
                return this.exitoField;
            }
            set {
                if ((this.exitoField.Equals(value) != true)) {
                    this.exitoField = value;
                    this.RaisePropertyChanged("exito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] pdf {
            get {
                return this.pdfField;
            }
            set {
                if ((object.ReferenceEquals(this.pdfField, value) != true)) {
                    this.pdfField = value;
                    this.RaisePropertyChanged("pdf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                if ((object.ReferenceEquals(this.uuidField, value) != true)) {
                    this.uuidField = value;
                    this.RaisePropertyChanged("uuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xmlTimbrado {
            get {
                return this.xmlTimbradoField;
            }
            set {
                if ((object.ReferenceEquals(this.xmlTimbradoField, value) != true)) {
                    this.xmlTimbradoField = value;
                    this.RaisePropertyChanged("xmlTimbrado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCancelacion", Namespace="http://schemas.datacontract.org/2004/07/WcfIntegral33")]
    [System.SerializableAttribute()]
    public partial class RespuestaCancelacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string acuseCancelacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool exitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensaje_errorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string acuseCancelacion {
            get {
                return this.acuseCancelacionField;
            }
            set {
                if ((object.ReferenceEquals(this.acuseCancelacionField, value) != true)) {
                    this.acuseCancelacionField = value;
                    this.RaisePropertyChanged("acuseCancelacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool exito {
            get {
                return this.exitoField;
            }
            set {
                if ((this.exitoField.Equals(value) != true)) {
                    this.exitoField = value;
                    this.RaisePropertyChanged("exito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje_error {
            get {
                return this.mensaje_errorField;
            }
            set {
                if ((object.ReferenceEquals(this.mensaje_errorField, value) != true)) {
                    this.mensaje_errorField = value;
                    this.RaisePropertyChanged("mensaje_error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCancelacionV2", Namespace="http://schemas.datacontract.org/2004/07/WcfIntegral33")]
    [System.SerializableAttribute()]
    public partial class RespuestaCancelacionV2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPAP.WsIntegral33Pruebas.DetalleCancelacion[] DetallesCancelacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorDetalladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OperacionExitosaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLAcuseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPAP.WsIntegral33Pruebas.DetalleCancelacion[] DetallesCancelacion {
            get {
                return this.DetallesCancelacionField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallesCancelacionField, value) != true)) {
                    this.DetallesCancelacionField = value;
                    this.RaisePropertyChanged("DetallesCancelacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeErrorDetallado {
            get {
                return this.MensajeErrorDetalladoField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorDetalladoField, value) != true)) {
                    this.MensajeErrorDetalladoField = value;
                    this.RaisePropertyChanged("MensajeErrorDetallado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa {
            get {
                return this.OperacionExitosaField;
            }
            set {
                if ((this.OperacionExitosaField.Equals(value) != true)) {
                    this.OperacionExitosaField = value;
                    this.RaisePropertyChanged("OperacionExitosa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLAcuse {
            get {
                return this.XMLAcuseField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLAcuseField, value) != true)) {
                    this.XMLAcuseField = value;
                    this.RaisePropertyChanged("XMLAcuse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleCancelacion", Namespace="http://schemas.datacontract.org/2004/07/WcfIntegral33")]
    [System.SerializableAttribute()]
    public partial class DetalleCancelacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EsCancelableFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoResultado {
            get {
                return this.CodigoResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoResultadoField, value) != true)) {
                    this.CodigoResultadoField = value;
                    this.RaisePropertyChanged("CodigoResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsCancelableField {
            get {
                return this.EsCancelableFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.EsCancelableFieldField, value) != true)) {
                    this.EsCancelableFieldField = value;
                    this.RaisePropertyChanged("EsCancelableField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeResultado {
            get {
                return this.MensajeResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeResultadoField, value) != true)) {
                    this.MensajeResultadoField = value;
                    this.RaisePropertyChanged("MensajeResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UUIDField, value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaPeticionesPendientes", Namespace="http://schemas.datacontract.org/2004/07/WcfIntegral33")]
    [System.SerializableAttribute()]
    public partial class RespuestaPeticionesPendientes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorDetalladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OperacionExitosaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] UUIDsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRespuesta {
            get {
                return this.CodigoRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoRespuestaField, value) != true)) {
                    this.CodigoRespuestaField = value;
                    this.RaisePropertyChanged("CodigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeErrorDetallado {
            get {
                return this.MensajeErrorDetalladoField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorDetalladoField, value) != true)) {
                    this.MensajeErrorDetalladoField = value;
                    this.RaisePropertyChanged("MensajeErrorDetallado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa {
            get {
                return this.OperacionExitosaField;
            }
            set {
                if ((this.OperacionExitosaField.Equals(value) != true)) {
                    this.OperacionExitosaField = value;
                    this.RaisePropertyChanged("OperacionExitosa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] UUIDs {
            get {
                return this.UUIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.UUIDsField, value) != true)) {
                    this.UUIDsField = value;
                    this.RaisePropertyChanged("UUIDs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UUIDProcesarRespuesta", Namespace="http://schemas.datacontract.org/2004/07/WcfIntegral33")]
    [System.SerializableAttribute()]
    public partial class UUIDProcesarRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AceptarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aceptar {
            get {
                return this.AceptarField;
            }
            set {
                if ((this.AceptarField.Equals(value) != true)) {
                    this.AceptarField = value;
                    this.RaisePropertyChanged("Aceptar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UUIDField, value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaAceptacionRechazo", Namespace="http://schemas.datacontract.org/2004/07/WcfIntegral33")]
    [System.SerializableAttribute()]
    public partial class RespuestaAceptacionRechazo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPAP.WsIntegral33Pruebas.FolioRespuesta[] FoliosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorDetalladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OperacionExitosaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLAcuseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRespuesta {
            get {
                return this.CodigoRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoRespuestaField, value) != true)) {
                    this.CodigoRespuestaField = value;
                    this.RaisePropertyChanged("CodigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPAP.WsIntegral33Pruebas.FolioRespuesta[] Folios {
            get {
                return this.FoliosField;
            }
            set {
                if ((object.ReferenceEquals(this.FoliosField, value) != true)) {
                    this.FoliosField = value;
                    this.RaisePropertyChanged("Folios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeErrorDetallado {
            get {
                return this.MensajeErrorDetalladoField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorDetalladoField, value) != true)) {
                    this.MensajeErrorDetalladoField = value;
                    this.RaisePropertyChanged("MensajeErrorDetallado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa {
            get {
                return this.OperacionExitosaField;
            }
            set {
                if ((this.OperacionExitosaField.Equals(value) != true)) {
                    this.OperacionExitosaField = value;
                    this.RaisePropertyChanged("OperacionExitosa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFCReceptor {
            get {
                return this.RFCReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCReceptorField, value) != true)) {
                    this.RFCReceptorField = value;
                    this.RaisePropertyChanged("RFCReceptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLAcuse {
            get {
                return this.XMLAcuseField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLAcuseField, value) != true)) {
                    this.XMLAcuseField = value;
                    this.RaisePropertyChanged("XMLAcuse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolioRespuesta", Namespace="http://schemas.datacontract.org/2004/07/WcfIntegral33")]
    [System.SerializableAttribute()]
    public partial class FolioRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstatusUUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstatusUUID {
            get {
                return this.EstatusUUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EstatusUUIDField, value) != true)) {
                    this.EstatusUUIDField = value;
                    this.RaisePropertyChanged("EstatusUUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UUIDField, value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaRelacionados", Namespace="http://schemas.datacontract.org/2004/07/WcfIntegral33")]
    [System.SerializableAttribute()]
    public partial class RespuestaRelacionados : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OperacionExitosaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPAP.WsIntegral33Pruebas.Relacionados RelacionadosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa {
            get {
                return this.OperacionExitosaField;
            }
            set {
                if ((this.OperacionExitosaField.Equals(value) != true)) {
                    this.OperacionExitosaField = value;
                    this.RaisePropertyChanged("OperacionExitosa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPAP.WsIntegral33Pruebas.Relacionados Relacionados {
            get {
                return this.RelacionadosField;
            }
            set {
                if ((object.ReferenceEquals(this.RelacionadosField, value) != true)) {
                    this.RelacionadosField = value;
                    this.RaisePropertyChanged("Relacionados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Relacionados", Namespace="http://schemas.datacontract.org/2004/07/WcfIntegral33")]
    [System.SerializableAttribute()]
    public partial class Relacionados : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UuidConsultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPAP.WsIntegral33Pruebas.UUID[] UuidsRelacionadosHijosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPAP.WsIntegral33Pruebas.UUID[] UuidsRelacionadosPadresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UuidConsultado {
            get {
                return this.UuidConsultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.UuidConsultadoField, value) != true)) {
                    this.UuidConsultadoField = value;
                    this.RaisePropertyChanged("UuidConsultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPAP.WsIntegral33Pruebas.UUID[] UuidsRelacionadosHijos {
            get {
                return this.UuidsRelacionadosHijosField;
            }
            set {
                if ((object.ReferenceEquals(this.UuidsRelacionadosHijosField, value) != true)) {
                    this.UuidsRelacionadosHijosField = value;
                    this.RaisePropertyChanged("UuidsRelacionadosHijos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPAP.WsIntegral33Pruebas.UUID[] UuidsRelacionadosPadres {
            get {
                return this.UuidsRelacionadosPadresField;
            }
            set {
                if ((object.ReferenceEquals(this.UuidsRelacionadosPadresField, value) != true)) {
                    this.UuidsRelacionadosPadresField = value;
                    this.RaisePropertyChanged("UuidsRelacionadosPadres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UUID", Namespace="http://schemas.datacontract.org/2004/07/WcfIntegral33")]
    [System.SerializableAttribute()]
    public partial class UUID : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RfcEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RfcReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UuidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RfcEmisor {
            get {
                return this.RfcEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.RfcEmisorField, value) != true)) {
                    this.RfcEmisorField = value;
                    this.RaisePropertyChanged("RfcEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RfcReceptor {
            get {
                return this.RfcReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.RfcReceptorField, value) != true)) {
                    this.RfcReceptorField = value;
                    this.RaisePropertyChanged("RfcReceptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uuid {
            get {
                return this.UuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UuidField, value) != true)) {
                    this.UuidField = value;
                    this.RaisePropertyChanged("Uuid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsIntegral33Pruebas.IWsCFDI33")]
    public interface IWsCFDI33 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/TimbrarTxt", ReplyAction="http://tempuri.org/IWsCFDI33/TimbrarTxtResponse")]
        SOAPAP.WsIntegral33Pruebas.Respuesta TimbrarTxt(SOAPAP.WsIntegral33Pruebas.Peticion _pet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/TimbrarTxt", ReplyAction="http://tempuri.org/IWsCFDI33/TimbrarTxtResponse")]
        System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.Respuesta> TimbrarTxtAsync(SOAPAP.WsIntegral33Pruebas.Peticion _pet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/Sellar", ReplyAction="http://tempuri.org/IWsCFDI33/SellarResponse")]
        SOAPAP.WsIntegral33Pruebas.Respuesta Sellar(string varuser, string varpas, string xmlContenido, string dAdicionales, bool productivo, int tipoCFDI, string cadenaComplemento, bool pdf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/Sellar", ReplyAction="http://tempuri.org/IWsCFDI33/SellarResponse")]
        System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.Respuesta> SellarAsync(string varuser, string varpas, string xmlContenido, string dAdicionales, bool productivo, int tipoCFDI, string cadenaComplemento, bool pdf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/Timbrado_bd", ReplyAction="http://tempuri.org/IWsCFDI33/Timbrado_bdResponse")]
        string[] Timbrado_bd(string usuario, string contrasena, string xml_Timbrar, string _referenciaTimbrado, bool productivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/Timbrado_bd", ReplyAction="http://tempuri.org/IWsCFDI33/Timbrado_bdResponse")]
        System.Threading.Tasks.Task<string[]> Timbrado_bdAsync(string usuario, string contrasena, string xml_Timbrar, string _referenciaTimbrado, bool productivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/ConsultaporEmisor", ReplyAction="http://tempuri.org/IWsCFDI33/ConsultaporEmisorResponse")]
        string[] ConsultaporEmisor(string usuario, string contrasena, string rfcEmisor, string fecha_Inicio, string fecha_Fin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/ConsultaporEmisor", ReplyAction="http://tempuri.org/IWsCFDI33/ConsultaporEmisorResponse")]
        System.Threading.Tasks.Task<string[]> ConsultaporEmisorAsync(string usuario, string contrasena, string rfcEmisor, string fecha_Inicio, string fecha_Fin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/TimbrarXMLconComplementos", ReplyAction="http://tempuri.org/IWsCFDI33/TimbrarXMLconComplementosResponse")]
        SOAPAP.WsIntegral33Pruebas.Respuesta TimbrarXMLconComplementos(string user, string password, string xmlconAdd, string rfcEmisor, int tipoCFDI, bool sellar, bool productivo, bool pdf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/TimbrarXMLconComplementos", ReplyAction="http://tempuri.org/IWsCFDI33/TimbrarXMLconComplementosResponse")]
        System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.Respuesta> TimbrarXMLconComplementosAsync(string user, string password, string xmlconAdd, string rfcEmisor, int tipoCFDI, bool sellar, bool productivo, bool pdf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/ObtenerXMLporUuid", ReplyAction="http://tempuri.org/IWsCFDI33/ObtenerXMLporUuidResponse")]
        SOAPAP.WsIntegral33Pruebas.Respuesta ObtenerXMLporUuid(string user, string password, string uuid, string rfcEmisor, bool pdf, int tipoCFDI, string adicionales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/ObtenerXMLporUuid", ReplyAction="http://tempuri.org/IWsCFDI33/ObtenerXMLporUuidResponse")]
        System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.Respuesta> ObtenerXMLporUuidAsync(string user, string password, string uuid, string rfcEmisor, bool pdf, int tipoCFDI, string adicionales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/CancelarCFDI", ReplyAction="http://tempuri.org/IWsCFDI33/CancelarCFDIResponse")]
        SOAPAP.WsIntegral33Pruebas.RespuestaCancelacion CancelarCFDI(string usuario, string contrasena, string rfcEmisor, string uuid, string certificadoPKCS12, string passwordPKCS12);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/CancelarCFDI", ReplyAction="http://tempuri.org/IWsCFDI33/CancelarCFDIResponse")]
        System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.RespuestaCancelacion> CancelarCFDIAsync(string usuario, string contrasena, string rfcEmisor, string uuid, string certificadoPKCS12, string passwordPKCS12);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/CancelarCFDIConValidacion", ReplyAction="http://tempuri.org/IWsCFDI33/CancelarCFDIConValidacionResponse")]
        SOAPAP.WsIntegral33Pruebas.RespuestaCancelacionV2 CancelarCFDIConValidacion(string usuario, string contrasena, string rfcEmisor, string uuid, string certificadoPKCS12, string passwordPKCS12);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/CancelarCFDIConValidacion", ReplyAction="http://tempuri.org/IWsCFDI33/CancelarCFDIConValidacionResponse")]
        System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.RespuestaCancelacionV2> CancelarCFDIConValidacionAsync(string usuario, string contrasena, string rfcEmisor, string uuid, string certificadoPKCS12, string passwordPKCS12);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/ObtenerPeticionesPendientesCancelacion", ReplyAction="http://tempuri.org/IWsCFDI33/ObtenerPeticionesPendientesCancelacionResponse")]
        SOAPAP.WsIntegral33Pruebas.RespuestaPeticionesPendientes ObtenerPeticionesPendientesCancelacion(string usuario, string contrasena, string rfcReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/ObtenerPeticionesPendientesCancelacion", ReplyAction="http://tempuri.org/IWsCFDI33/ObtenerPeticionesPendientesCancelacionResponse")]
        System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.RespuestaPeticionesPendientes> ObtenerPeticionesPendientesCancelacionAsync(string usuario, string contrasena, string rfcReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/ProcesarAceptacionRechazo", ReplyAction="http://tempuri.org/IWsCFDI33/ProcesarAceptacionRechazoResponse")]
        SOAPAP.WsIntegral33Pruebas.RespuestaAceptacionRechazo ProcesarAceptacionRechazo(string usuario, string contrasena, string rfcReceptor, SOAPAP.WsIntegral33Pruebas.UUIDProcesarRespuesta[] uuids, string certificadoPKCS12, string passwordPKCS12);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/ProcesarAceptacionRechazo", ReplyAction="http://tempuri.org/IWsCFDI33/ProcesarAceptacionRechazoResponse")]
        System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.RespuestaAceptacionRechazo> ProcesarAceptacionRechazoAsync(string usuario, string contrasena, string rfcReceptor, SOAPAP.WsIntegral33Pruebas.UUIDProcesarRespuesta[] uuids, string certificadoPKCS12, string passwordPKCS12);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/ConsultarComprobantesRelacionados", ReplyAction="http://tempuri.org/IWsCFDI33/ConsultarComprobantesRelacionadosResponse")]
        SOAPAP.WsIntegral33Pruebas.RespuestaRelacionados ConsultarComprobantesRelacionados(string usuario, string password, string UUID, string RFCReceptor, string pfxReceptorBase64, string passwdPfx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/ConsultarComprobantesRelacionados", ReplyAction="http://tempuri.org/IWsCFDI33/ConsultarComprobantesRelacionadosResponse")]
        System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.RespuestaRelacionados> ConsultarComprobantesRelacionadosAsync(string usuario, string password, string UUID, string RFCReceptor, string pfxReceptorBase64, string passwdPfx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/ObtenerPDF", ReplyAction="http://tempuri.org/IWsCFDI33/ObtenerPDFResponse")]
        SOAPAP.WsIntegral33Pruebas.ObtenerPDFResponse ObtenerPDF(SOAPAP.WsIntegral33Pruebas.ObtenerPDFRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/ObtenerPDF", ReplyAction="http://tempuri.org/IWsCFDI33/ObtenerPDFResponse")]
        System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.ObtenerPDFResponse> ObtenerPDFAsync(SOAPAP.WsIntegral33Pruebas.ObtenerPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/ObtenerPDFPakmail", ReplyAction="http://tempuri.org/IWsCFDI33/ObtenerPDFPakmailResponse")]
        SOAPAP.WsIntegral33Pruebas.ObtenerPDFPakmailResponse ObtenerPDFPakmail(SOAPAP.WsIntegral33Pruebas.ObtenerPDFPakmailRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/ObtenerPDFPakmail", ReplyAction="http://tempuri.org/IWsCFDI33/ObtenerPDFPakmailResponse")]
        System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.ObtenerPDFPakmailResponse> ObtenerPDFPakmailAsync(SOAPAP.WsIntegral33Pruebas.ObtenerPDFPakmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/TimbrarCFDI", ReplyAction="http://tempuri.org/IWsCFDI33/TimbrarCFDIResponse")]
        string[] TimbrarCFDI(string usuario, string password, string cadenaXML, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/TimbrarCFDI", ReplyAction="http://tempuri.org/IWsCFDI33/TimbrarCFDIResponse")]
        System.Threading.Tasks.Task<string[]> TimbrarCFDIAsync(string usuario, string password, string cadenaXML, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/ObtenerAcuseCancelacion", ReplyAction="http://tempuri.org/IWsCFDI33/ObtenerAcuseCancelacionResponse")]
        SOAPAP.WsIntegral33Pruebas.RespuestaCancelacionV2 ObtenerAcuseCancelacion(string usuario, string password, string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCFDI33/ObtenerAcuseCancelacion", ReplyAction="http://tempuri.org/IWsCFDI33/ObtenerAcuseCancelacionResponse")]
        System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.RespuestaCancelacionV2> ObtenerAcuseCancelacionAsync(string usuario, string password, string UUID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerPDF", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerPDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string xmlTimbrado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string adicionales;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int tipoCFDI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string error;
        
        public ObtenerPDFRequest() {
        }
        
        public ObtenerPDFRequest(string user, string password, string xmlTimbrado, string adicionales, string rfcEmisor, string uuid, int tipoCFDI, string error) {
            this.user = user;
            this.password = password;
            this.xmlTimbrado = xmlTimbrado;
            this.adicionales = adicionales;
            this.rfcEmisor = rfcEmisor;
            this.uuid = uuid;
            this.tipoCFDI = tipoCFDI;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerPDFResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] ObtenerPDFResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        public ObtenerPDFResponse() {
        }
        
        public ObtenerPDFResponse(byte[] ObtenerPDFResult, string error) {
            this.ObtenerPDFResult = ObtenerPDFResult;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerPDFPakmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerPDFPakmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string xmlTimbrado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string adicionales;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int tipoCFDI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string error;
        
        public ObtenerPDFPakmailRequest() {
        }
        
        public ObtenerPDFPakmailRequest(string user, string password, string xmlTimbrado, string adicionales, string rfcEmisor, string uuid, int tipoCFDI, string error) {
            this.user = user;
            this.password = password;
            this.xmlTimbrado = xmlTimbrado;
            this.adicionales = adicionales;
            this.rfcEmisor = rfcEmisor;
            this.uuid = uuid;
            this.tipoCFDI = tipoCFDI;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerPDFPakmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerPDFPakmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] ObtenerPDFPakmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        public ObtenerPDFPakmailResponse() {
        }
        
        public ObtenerPDFPakmailResponse(byte[] ObtenerPDFPakmailResult, string error) {
            this.ObtenerPDFPakmailResult = ObtenerPDFPakmailResult;
            this.error = error;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsCFDI33Channel : SOAPAP.WsIntegral33Pruebas.IWsCFDI33, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsCFDI33Client : System.ServiceModel.ClientBase<SOAPAP.WsIntegral33Pruebas.IWsCFDI33>, SOAPAP.WsIntegral33Pruebas.IWsCFDI33 {
        
        public WsCFDI33Client() {
        }
        
        public WsCFDI33Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsCFDI33Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsCFDI33Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsCFDI33Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPAP.WsIntegral33Pruebas.Respuesta TimbrarTxt(SOAPAP.WsIntegral33Pruebas.Peticion _pet) {
            return base.Channel.TimbrarTxt(_pet);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.Respuesta> TimbrarTxtAsync(SOAPAP.WsIntegral33Pruebas.Peticion _pet) {
            return base.Channel.TimbrarTxtAsync(_pet);
        }
        
        public SOAPAP.WsIntegral33Pruebas.Respuesta Sellar(string varuser, string varpas, string xmlContenido, string dAdicionales, bool productivo, int tipoCFDI, string cadenaComplemento, bool pdf) {
            return base.Channel.Sellar(varuser, varpas, xmlContenido, dAdicionales, productivo, tipoCFDI, cadenaComplemento, pdf);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.Respuesta> SellarAsync(string varuser, string varpas, string xmlContenido, string dAdicionales, bool productivo, int tipoCFDI, string cadenaComplemento, bool pdf) {
            return base.Channel.SellarAsync(varuser, varpas, xmlContenido, dAdicionales, productivo, tipoCFDI, cadenaComplemento, pdf);
        }
        
        public string[] Timbrado_bd(string usuario, string contrasena, string xml_Timbrar, string _referenciaTimbrado, bool productivo) {
            return base.Channel.Timbrado_bd(usuario, contrasena, xml_Timbrar, _referenciaTimbrado, productivo);
        }
        
        public System.Threading.Tasks.Task<string[]> Timbrado_bdAsync(string usuario, string contrasena, string xml_Timbrar, string _referenciaTimbrado, bool productivo) {
            return base.Channel.Timbrado_bdAsync(usuario, contrasena, xml_Timbrar, _referenciaTimbrado, productivo);
        }
        
        public string[] ConsultaporEmisor(string usuario, string contrasena, string rfcEmisor, string fecha_Inicio, string fecha_Fin) {
            return base.Channel.ConsultaporEmisor(usuario, contrasena, rfcEmisor, fecha_Inicio, fecha_Fin);
        }
        
        public System.Threading.Tasks.Task<string[]> ConsultaporEmisorAsync(string usuario, string contrasena, string rfcEmisor, string fecha_Inicio, string fecha_Fin) {
            return base.Channel.ConsultaporEmisorAsync(usuario, contrasena, rfcEmisor, fecha_Inicio, fecha_Fin);
        }
        
        public SOAPAP.WsIntegral33Pruebas.Respuesta TimbrarXMLconComplementos(string user, string password, string xmlconAdd, string rfcEmisor, int tipoCFDI, bool sellar, bool productivo, bool pdf) {
            return base.Channel.TimbrarXMLconComplementos(user, password, xmlconAdd, rfcEmisor, tipoCFDI, sellar, productivo, pdf);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.Respuesta> TimbrarXMLconComplementosAsync(string user, string password, string xmlconAdd, string rfcEmisor, int tipoCFDI, bool sellar, bool productivo, bool pdf) {
            return base.Channel.TimbrarXMLconComplementosAsync(user, password, xmlconAdd, rfcEmisor, tipoCFDI, sellar, productivo, pdf);
        }
        
        public SOAPAP.WsIntegral33Pruebas.Respuesta ObtenerXMLporUuid(string user, string password, string uuid, string rfcEmisor, bool pdf, int tipoCFDI, string adicionales) {
            return base.Channel.ObtenerXMLporUuid(user, password, uuid, rfcEmisor, pdf, tipoCFDI, adicionales);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.Respuesta> ObtenerXMLporUuidAsync(string user, string password, string uuid, string rfcEmisor, bool pdf, int tipoCFDI, string adicionales) {
            return base.Channel.ObtenerXMLporUuidAsync(user, password, uuid, rfcEmisor, pdf, tipoCFDI, adicionales);
        }
        
        public SOAPAP.WsIntegral33Pruebas.RespuestaCancelacion CancelarCFDI(string usuario, string contrasena, string rfcEmisor, string uuid, string certificadoPKCS12, string passwordPKCS12) {
            return base.Channel.CancelarCFDI(usuario, contrasena, rfcEmisor, uuid, certificadoPKCS12, passwordPKCS12);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.RespuestaCancelacion> CancelarCFDIAsync(string usuario, string contrasena, string rfcEmisor, string uuid, string certificadoPKCS12, string passwordPKCS12) {
            return base.Channel.CancelarCFDIAsync(usuario, contrasena, rfcEmisor, uuid, certificadoPKCS12, passwordPKCS12);
        }
        
        public SOAPAP.WsIntegral33Pruebas.RespuestaCancelacionV2 CancelarCFDIConValidacion(string usuario, string contrasena, string rfcEmisor, string uuid, string certificadoPKCS12, string passwordPKCS12) {
            return base.Channel.CancelarCFDIConValidacion(usuario, contrasena, rfcEmisor, uuid, certificadoPKCS12, passwordPKCS12);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.RespuestaCancelacionV2> CancelarCFDIConValidacionAsync(string usuario, string contrasena, string rfcEmisor, string uuid, string certificadoPKCS12, string passwordPKCS12) {
            return base.Channel.CancelarCFDIConValidacionAsync(usuario, contrasena, rfcEmisor, uuid, certificadoPKCS12, passwordPKCS12);
        }
        
        public SOAPAP.WsIntegral33Pruebas.RespuestaPeticionesPendientes ObtenerPeticionesPendientesCancelacion(string usuario, string contrasena, string rfcReceptor) {
            return base.Channel.ObtenerPeticionesPendientesCancelacion(usuario, contrasena, rfcReceptor);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.RespuestaPeticionesPendientes> ObtenerPeticionesPendientesCancelacionAsync(string usuario, string contrasena, string rfcReceptor) {
            return base.Channel.ObtenerPeticionesPendientesCancelacionAsync(usuario, contrasena, rfcReceptor);
        }
        
        public SOAPAP.WsIntegral33Pruebas.RespuestaAceptacionRechazo ProcesarAceptacionRechazo(string usuario, string contrasena, string rfcReceptor, SOAPAP.WsIntegral33Pruebas.UUIDProcesarRespuesta[] uuids, string certificadoPKCS12, string passwordPKCS12) {
            return base.Channel.ProcesarAceptacionRechazo(usuario, contrasena, rfcReceptor, uuids, certificadoPKCS12, passwordPKCS12);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.RespuestaAceptacionRechazo> ProcesarAceptacionRechazoAsync(string usuario, string contrasena, string rfcReceptor, SOAPAP.WsIntegral33Pruebas.UUIDProcesarRespuesta[] uuids, string certificadoPKCS12, string passwordPKCS12) {
            return base.Channel.ProcesarAceptacionRechazoAsync(usuario, contrasena, rfcReceptor, uuids, certificadoPKCS12, passwordPKCS12);
        }
        
        public SOAPAP.WsIntegral33Pruebas.RespuestaRelacionados ConsultarComprobantesRelacionados(string usuario, string password, string UUID, string RFCReceptor, string pfxReceptorBase64, string passwdPfx) {
            return base.Channel.ConsultarComprobantesRelacionados(usuario, password, UUID, RFCReceptor, pfxReceptorBase64, passwdPfx);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.RespuestaRelacionados> ConsultarComprobantesRelacionadosAsync(string usuario, string password, string UUID, string RFCReceptor, string pfxReceptorBase64, string passwdPfx) {
            return base.Channel.ConsultarComprobantesRelacionadosAsync(usuario, password, UUID, RFCReceptor, pfxReceptorBase64, passwdPfx);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPAP.WsIntegral33Pruebas.ObtenerPDFResponse SOAPAP.WsIntegral33Pruebas.IWsCFDI33.ObtenerPDF(SOAPAP.WsIntegral33Pruebas.ObtenerPDFRequest request) {
            return base.Channel.ObtenerPDF(request);
        }
        
        public byte[] ObtenerPDF(string user, string password, string xmlTimbrado, string adicionales, string rfcEmisor, string uuid, int tipoCFDI, ref string error) {
            SOAPAP.WsIntegral33Pruebas.ObtenerPDFRequest inValue = new SOAPAP.WsIntegral33Pruebas.ObtenerPDFRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.xmlTimbrado = xmlTimbrado;
            inValue.adicionales = adicionales;
            inValue.rfcEmisor = rfcEmisor;
            inValue.uuid = uuid;
            inValue.tipoCFDI = tipoCFDI;
            inValue.error = error;
            SOAPAP.WsIntegral33Pruebas.ObtenerPDFResponse retVal = ((SOAPAP.WsIntegral33Pruebas.IWsCFDI33)(this)).ObtenerPDF(inValue);
            error = retVal.error;
            return retVal.ObtenerPDFResult;
        }
        
        public System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.ObtenerPDFResponse> ObtenerPDFAsync(SOAPAP.WsIntegral33Pruebas.ObtenerPDFRequest request) {
            return base.Channel.ObtenerPDFAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPAP.WsIntegral33Pruebas.ObtenerPDFPakmailResponse SOAPAP.WsIntegral33Pruebas.IWsCFDI33.ObtenerPDFPakmail(SOAPAP.WsIntegral33Pruebas.ObtenerPDFPakmailRequest request) {
            return base.Channel.ObtenerPDFPakmail(request);
        }
        
        public byte[] ObtenerPDFPakmail(string user, string password, string xmlTimbrado, string adicionales, string rfcEmisor, string uuid, int tipoCFDI, ref string error) {
            SOAPAP.WsIntegral33Pruebas.ObtenerPDFPakmailRequest inValue = new SOAPAP.WsIntegral33Pruebas.ObtenerPDFPakmailRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.xmlTimbrado = xmlTimbrado;
            inValue.adicionales = adicionales;
            inValue.rfcEmisor = rfcEmisor;
            inValue.uuid = uuid;
            inValue.tipoCFDI = tipoCFDI;
            inValue.error = error;
            SOAPAP.WsIntegral33Pruebas.ObtenerPDFPakmailResponse retVal = ((SOAPAP.WsIntegral33Pruebas.IWsCFDI33)(this)).ObtenerPDFPakmail(inValue);
            error = retVal.error;
            return retVal.ObtenerPDFPakmailResult;
        }
        
        public System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.ObtenerPDFPakmailResponse> ObtenerPDFPakmailAsync(SOAPAP.WsIntegral33Pruebas.ObtenerPDFPakmailRequest request) {
            return base.Channel.ObtenerPDFPakmailAsync(request);
        }
        
        public string[] TimbrarCFDI(string usuario, string password, string cadenaXML, string referencia) {
            return base.Channel.TimbrarCFDI(usuario, password, cadenaXML, referencia);
        }
        
        public System.Threading.Tasks.Task<string[]> TimbrarCFDIAsync(string usuario, string password, string cadenaXML, string referencia) {
            return base.Channel.TimbrarCFDIAsync(usuario, password, cadenaXML, referencia);
        }
        
        public SOAPAP.WsIntegral33Pruebas.RespuestaCancelacionV2 ObtenerAcuseCancelacion(string usuario, string password, string UUID) {
            return base.Channel.ObtenerAcuseCancelacion(usuario, password, UUID);
        }
        
        public System.Threading.Tasks.Task<SOAPAP.WsIntegral33Pruebas.RespuestaCancelacionV2> ObtenerAcuseCancelacionAsync(string usuario, string password, string UUID) {
            return base.Channel.ObtenerAcuseCancelacionAsync(usuario, password, UUID);
        }
    }
}
